### ISSUE TITLE
uavcan.equipment.actuator.Command default data type ID

### ISSUE THREAD

**Issue by flybrianfly** [dronecan/libuavcan#6]
Why does the message uavcan.equipment.actuator.Command not have a default data type ID? It's autogenerated from the libuavcan DSDL compiler, my assumption based on code comments would be that it should have a default data type ID and be registered with the GlobalDataTypeRegistry.

**Comment by flybrianfly** [comment]
Is it a correct assumption that we're only meant to use ArrayCommand and that the Command message isn't supposed to be used directly?

**Comment by tridge** [comment]
> Is it a correct assumption that we're only meant to use ArrayCommand and that the Command message isn't supposed to be used directly?

yes, that is correct
